<?php
/**
 * Created by PhpStorm.
 * User: Nicolas
 * Date: 10/02/2015
 * Time: 13:48
 */

date_default_timezone_set("Europe/Paris");
setlocale (LC_TIME, 'fr_FR.utf8','fra');

// Securisation des données POST, NEVER TRUST USERS'S INPUT!
foreach ( $_POST as $Key => $Value ) {
    $_POST[$Key] = htmlspecialchars($Value, ENT_QUOTES);
}

require_once 'connect.php';

if ( isset($_POST["name"], $_POST['pass1']) ) {

    $UserQuery = "SELECT SQL_CALC_FOUND_ROWS *
        FROM users
        WHERE nameUser = '" . $_POST["name"] . "';
    ";

    $DBObject = $db->query($UserQuery);
    $DBObject->setFetchMode(PDO::FETCH_OBJ);
    $User     = $DBObject->fetch();

    // MD5 DEPRECATED, USE PASSWORD_HASH
    if ( $User ) {
        if ( password_verify($_POST["pass1"], $User->password ) ) {
            $Hash = hash("sha256", $User->nameUser);
            $SessionQuery = "SELECT SQL_CALC_FOUND_ROWS *
                FROM sessions
                WHERE session_sess_id = '$Hash';
            ";

            $DBObject = $db->query($SessionQuery);
            $DBObject->setFetchMode(PDO::FETCH_OBJ);
            $Session  = $DBObject->fetch();

            if ( $Session ) {
                $UpdateQuery = "UPDATE sessions SET
                    session_date_modification = NOW(),
                    session_expiration = '" . date("Y-m-d H:i:s", mktime(date("H"), date("i"), date("s"), date("n"), date("j") + 3, date("Y"))) . "'
                    WHERE session_sess_id = '$Hash';
                ";

                $db->query($UpdateQuery);
            } else {
                $InsertQuery = "INSERT INTO sessions SET
                    session_sess_id = '$Hash',
                    session_expiration = '" . date("Y-m-d H:i:s", mktime(date("H"), date("i"), date("s"), date("n"), date("j") + 3, date("Y"))) . "',
                    session_date_creation = NOW();
                ";

                $db->query($InsertQuery);
            }

            // FETCHING THE CHARACTER'S NAME
            $id = $User->idUser;
            $characterQuery = "SELECT nameCharacter
                    FROM characters
                    WHERE idUSer = '$id';
            ";

            $DBObject = $db->query($characterQuery);
            $DBObject->setFetchMode(PDO::FETCH_OBJ);
            
            $Character = $DBObject->fetch();

            // STARTING THE SESSION
            // Custom SESSID generated by secured sha256 function
            session_id($Hash);
            var_dump($Hash);
            session_start();

            $_SESSION['nameCharacter'] = $Character->nameCharacter;
            header('Location: ../welcome.php');
        } else {
            header('Location: ../nomatch.php');
        }
    } else {
        header('Location: ../nologin.php');
    }
}
// } else
// {
//     echo "Veuillez réessayer";
// }